server:
  port: 8607

spring:
  application:
    name: mogu-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 159.75.247.241:8848
      config:
        server-addr: 159.75.247.241:8848
        file-extension: yaml
        group: dev
