pipeline {
    agent any

    stages {
        stage('拉取代码') {
            steps {
              checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[credentialsId: '72f3026a-6d5f-4b2c-9483-a87811491046', url: 'git@gitee.com:white_white_123456/blog.git']]])
            }
        }
        stage('构建项目') {
            steps {
                sh 'mvn clean package  -Dmaven.test.skip=true docker:build docker:push'
            }
        }
          stage('推送项目') {
            steps {
                echo $WORKSPACE
                echo $BUILD_NUMBER
                echo '推送项目成功=='
            }
        }
    }
}
