version: '3.1'
services:
  rabbitmq:
    restart: always
    image: rabbitmq:3.9.12-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: peiqi666
    volumes:
      - /mydata/volumes/data/rabbitmq_data:/var/lib/rabbitmq/mnesia
    networks:
      - stack
      
networks:
  stack:
    driver: bridge


